const status = "authenticated";

const categories = [
  {
    id: "21",
    title: "Action",
    slug: "action",
    color: "#e74c3c",
  },
  {
    id: "22",
    title: "Adventure",
    slug: "adventure",
    color: "#3498db",
  },
  {
    id: "23",
    title: "Comedy",
    slug: "comedy",
    color: "#f39c12",
  },
  {
    id: "24",
    title: "Drama",
    slug: "drama",
    color: "#9b59b6",
  },
  {
    id: "25",
    title: "Fantasy",
    slug: "fantasy",
    color: "#2ecc71",
  },
  {
    id: "26",
    title: "Romance",
    slug: "romance",
    color: "#e91e63",
  },
  {
    id: "27",
    title: "Slice of Life",
    slug: "slice-of-life",
    color: "#00bcd4",
  },
  {
    id: "28",
    title: "Science Fiction",
    slug: "science-fiction",
    color: "#607d8b",
  },
  {
    id: "29",
    title: "Horror",
    slug: "horror",
    color: "#c0392b",
  },
  {
    id: "20",
    title: "Mystery",
    slug: "mystery",
    color: "#9e9e9e",
  },
];

//  const posts = [
//   {
//     id: "1",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "2",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },

//   {
//     id: "3",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "4",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },
//   {
//     id: "5",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "6",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },
//   {
//     id: "7",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "8",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },
// ];

module.exports = {
  status,
  categories,
  // posts,
};
