const status = "authenticated";

const categories = [
  {
    id: "11",
    title: "Ficción",
    slug: "ficcion",
    color: "#ffb04f45",
  },
  {
    id: "12",
    title: "No ficción",
    slug: "no-ficcion",
    color: "#4fbff045",
  },
  {
    id: "13",
    title: "Misterio",
    slug: "misterio",
    color: "#4f45ff45",
  },
  {
    id: "14",
    title: "Ciencia ficción",
    slug: "ciencia-ficcion",
    color: "#ff4f4f45",
  },
  {
    id: "15",
    title: "Fantasía",
    slug: "fantasia",
    color: "#4f45ffbf",
  },
];

//  const posts = [
//   {
//     id: "1",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "2",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },

//   {
//     id: "3",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "4",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },
//   {
//     id: "5",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "6",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },
//   {
//     id: "7",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js",
//     title: "Next JS",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702391820/nqethq3gzldpty0xmkw3.jpg",
//     views: 100,
//     catSlug: "next-js",
//     cat: {
//       id: "1",
//       title: "Next JS",
//       slug: "next-js",
//       color: "#dddddd",
//     },
//   },
//   {
//     id: "8",
//     createdAt: new Date("2021-01-01"),
//     slug: "next-js-with-prisma",
//     title: "Next JS with Prisma",
//     desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptates.",
//     img: "https://res.cloudinary.com/dqcoo1wnq/image/upload/v1702275296/swz5vbykpoiilhgmwtus.webp",
//     views: 100,
//     catSlug: "prisma",
//     cat: {
//       id: "2",
//       title: "Prisma",
//       slug: "prisma",
//       color: "#7fb88133",
//     },
//   },
// ];

module.exports = {
  status,
  categories,
  // posts,
};
